// Generated by Selenium IDE
// Created by Taekmin Jeong
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
namespace TJAssignment3
{
    [TestFixture]
    public class TJAssignment3SuiteTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;

        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }

        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }

        public string waitForWindow(int timeout)
        {
            try
            {
                Thread.Sleep(timeout);
            }
            catch (Exception e)
            {
                Console.WriteLine("{0} Exception caught.", e);
            }
            var whNow = ((IReadOnlyCollection<object>)driver.WindowHandles).ToList();
            var whThen = ((IReadOnlyCollection<object>)vars["WindowHandles"]).ToList();
            if (whNow.Count > whThen.Count)
            {
                return whNow.Except(whThen).First().ToString();
            }
            else
            {
                return whNow.First().ToString();
            }
        }

        [Test]
        public void Submit_EnterNothing_ErrorFieldRequired()
        {
            //Arrange
            driver.Navigate().GoToUrl("http://localhost:4000/");
            driver.Manage().Window.Size = new System.Drawing.Size(788, 824);
            //Act
            driver.FindElement(By.Id("homeToForm")).Click();
            driver.FindElement(By.Id("submit")).Click();
            string message = driver.FindElement(By.Id("errors")).Text;
            Console.WriteLine(message);
            //Assert
            Assert.AreEqual(message, "Enter first name\r\n" +
                "Enter last name\r\nEnter city\r\nEnter province\r\n" +
                "Enter postal code\r\nEnter phone number\r\nEnter email\r\n" +
                "Enter make\r\nEnter model\r\nEnter year");
        }
        [Test]
        public void Submit_EnterWrongEmail_EmailWrongFormat()
        {
            //Arrange
            driver.Navigate().GoToUrl("http://localhost:4000/");
            driver.Manage().Window.Size = new System.Drawing.Size(792, 824);
            //Act
            driver.FindElement(By.Id("homeToForm")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Taekmin");
            driver.FindElement(By.Id("lastName")).SendKeys("Jeong");
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("province")).SendKeys("Ontario");
            driver.FindElement(By.Id("postalCode")).SendKeys("N2L 5M1");
            driver.FindElement(By.Id("phoneNumber")).SendKeys("519-778-5471");
            driver.FindElement(By.Id("email")).SendKeys("tingmon2gmail.m");
            driver.FindElement(By.Id("make")).SendKeys("");
            driver.FindElement(By.Id("model")).SendKeys("");
            driver.FindElement(By.Id("year")).SendKeys("");
            driver.FindElement(By.Id("phoneNumber")).Click();
            driver.FindElement(By.CssSelector("html")).Click();
            driver.FindElement(By.Id("make")).SendKeys("ford");
            driver.FindElement(By.Id("model")).SendKeys("mustang");
            driver.FindElement(By.Id("year")).SendKeys("2012");
            driver.FindElement(By.Id("submit")).Click();
            string message = driver.FindElement(By.Id("errors")).Text;
            Console.WriteLine(message);
            //Assert
            Assert.AreEqual(message, "Invalid email pattern");
        }
        [Test]
        public void Submit_EnterWrongPhone_PhoneWrongFormat()
        {
            //Arrange
            driver.Navigate().GoToUrl("http://localhost:4000/");
            driver.Manage().Window.Size = new System.Drawing.Size(792, 824);
            //Act
            driver.FindElement(By.Id("homeToForm")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Taekmin");
            driver.FindElement(By.Id("lastName")).SendKeys("Jeong");
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("province")).SendKeys("Ontario");
            driver.FindElement(By.Id("postalCode")).SendKeys("N2L 5M1");
            driver.FindElement(By.Id("phoneNumber")).SendKeys("5197785471");
            driver.FindElement(By.Id("email")).SendKeys("tingmon2@gmail.com");
            driver.FindElement(By.Id("make")).SendKeys("");
            driver.FindElement(By.Id("model")).SendKeys("");
            driver.FindElement(By.Id("year")).SendKeys("");
            driver.FindElement(By.Id("carform")).Click();
            driver.FindElement(By.Id("make")).SendKeys("ford");
            driver.FindElement(By.Id("model")).SendKeys("mustang");
            driver.FindElement(By.Id("year")).SendKeys("2012");
            driver.FindElement(By.Id("submit")).Click();
            string message = driver.FindElement(By.Id("errors")).Text;
            Console.WriteLine(message);
            //Assert
            Assert.AreEqual(message, "Invalid phone number pattern");
        }
        [Test]
        public void Submit_EnterWrongPostcode_PostcodeWrongFormat()
        {
            //Arrange
            driver.Navigate().GoToUrl("http://localhost:4000/");
            driver.Manage().Window.Size = new System.Drawing.Size(794, 824);
            //Act
            driver.FindElement(By.Id("homeToForm")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Taekmin");
            driver.FindElement(By.Id("lastName")).SendKeys("Jeong");
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("province")).SendKeys("Ontario");
            driver.FindElement(By.Id("postalCode")).SendKeys("1R3 M5M");
            driver.FindElement(By.Id("phoneNumber")).SendKeys("519-778-5471");
            driver.FindElement(By.Id("email")).SendKeys("tingmon2@gmail.com");
            driver.FindElement(By.Id("make")).SendKeys("");
            driver.FindElement(By.Id("model")).SendKeys("");
            driver.FindElement(By.Id("year")).SendKeys("");
            driver.FindElement(By.Id("make")).SendKeys("ford");
            driver.FindElement(By.Id("model")).SendKeys("mustang");
            driver.FindElement(By.Id("year")).SendKeys("2012");
            driver.FindElement(By.Id("carform")).Click();
            driver.FindElement(By.Id("submit")).Click();
            string message = driver.FindElement(By.Id("errors")).Text;
            Console.WriteLine(message);
            //Assert
            Assert.AreEqual(message, "Invalid postal code pattern");
        }
        [Test]
        public void Submit_EnterWrongYear_YearWrongFormat()
        {
            //Arrange
            driver.Navigate().GoToUrl("http://localhost:4000/");
            driver.Manage().Window.Size = new System.Drawing.Size(796, 824);
            //Act
            driver.FindElement(By.Id("homeToForm")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Taekmin");
            driver.FindElement(By.Id("lastName")).SendKeys("Jeong");
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("province")).SendKeys("Ontario");
            driver.FindElement(By.Id("postalCode")).SendKeys("N2L 5M1");
            driver.FindElement(By.Id("phoneNumber")).SendKeys("519-778-5471");
            driver.FindElement(By.Id("email")).SendKeys("tingmon2@gmail.com");
            driver.FindElement(By.Id("make")).SendKeys("");
            driver.FindElement(By.Id("model")).SendKeys("");
            driver.FindElement(By.Id("year")).SendKeys("asdf");
            driver.FindElement(By.Id("carform")).Click();
            driver.FindElement(By.Id("make")).SendKeys("ford");
            driver.FindElement(By.Id("model")).SendKeys("mustang");
            driver.FindElement(By.Id("submit")).Click();
            string message = driver.FindElement(By.Id("errors")).Text;
            Console.WriteLine(message);
            //Assert
            Assert.AreEqual(message, "Invalid year pattern");
        }
        [Test]
        public void Submit_EnterSpaceModelField_ModelFieldRequired()
        {
            //Arrange
            driver.Navigate().GoToUrl("http://localhost:4000/");
            driver.Manage().Window.Size = new System.Drawing.Size(796, 824);
            //Act
            driver.FindElement(By.Id("homeToForm")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Taekmin");
            driver.FindElement(By.Id("lastName")).SendKeys("Jeong");
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("province")).SendKeys("Ontario");
            driver.FindElement(By.Id("postalCode")).SendKeys("N2L 5M1");
            driver.FindElement(By.Id("phoneNumber")).SendKeys("519-778-5471");
            driver.FindElement(By.Id("email")).SendKeys("tingmon2@gmail.com");
            driver.FindElement(By.Id("make")).SendKeys("");
            driver.FindElement(By.Id("model")).SendKeys(" ");
            driver.FindElement(By.Id("year")).SendKeys("");
            driver.FindElement(By.CssSelector("html")).Click();
            driver.FindElement(By.Id("year")).SendKeys("2012");
            driver.FindElement(By.CssSelector("html")).Click();
            driver.FindElement(By.Id("make")).SendKeys("ford");
            driver.FindElement(By.Id("submit")).Click();
            string message = driver.FindElement(By.Id("errors")).Text;
            Console.WriteLine(message);
            //Assert
            Assert.AreEqual(message, "Enter model");
        }
        [Test]
        public void Submit_EnterValidInput_RecordSaved()
        {
            //Arrange
            driver.Navigate().GoToUrl("http://localhost:4000/");
            driver.Manage().Window.Size = new System.Drawing.Size(790, 824);
            //Act
            driver.FindElement(By.Id("homeToForm")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Taekmin");
            driver.FindElement(By.Id("lastName")).SendKeys("Jeong");
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("province")).SendKeys("Ontario");
            driver.FindElement(By.Id("postalCode")).SendKeys("N2L 5M1");
            driver.FindElement(By.Id("phoneNumber")).SendKeys("519-778-5471");
            driver.FindElement(By.Id("email")).SendKeys("tingmon2@gmail.com");
            driver.FindElement(By.Id("make")).SendKeys("");
            driver.FindElement(By.Id("model")).SendKeys("");
            driver.FindElement(By.Id("year")).SendKeys("");
            driver.FindElement(By.Id("make")).Click();
            driver.FindElement(By.Id("make")).SendKeys("ford");
            driver.FindElement(By.Id("model")).SendKeys("mustang");
            driver.FindElement(By.Id("year")).SendKeys("2012");
            driver.FindElement(By.Id("carform")).Click();
            driver.FindElement(By.Id("submit")).Click();
            string message = driver.FindElement(By.Id("errors")).Text;
            Console.WriteLine(message);
            //Assert
            Assert.AreEqual(message, "New Record Saved! Record Number: 1");
        }
        [Test]
        public void Submit_SubmitTwoRecords_SaveTwoRecords()
        {
            //Arrange
            driver.Navigate().GoToUrl("http://localhost:4000/");
            driver.Manage().Window.Size = new System.Drawing.Size(798, 824);
            //Act
            driver.FindElement(By.Id("homeToForm")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Taekmin");
            driver.FindElement(By.Id("lastName")).SendKeys("Jeong");
            driver.FindElement(By.Id("city")).SendKeys("Waterloo");
            driver.FindElement(By.Id("province")).SendKeys("Ontario");
            driver.FindElement(By.Id("postalCode")).SendKeys("N2L 5M1");
            driver.FindElement(By.Id("phoneNumber")).SendKeys("519-778-5471");
            driver.FindElement(By.Id("email")).SendKeys("tingmon2@gmail.com");
            driver.FindElement(By.Id("make")).SendKeys("");
            driver.FindElement(By.Id("model")).SendKeys("");
            driver.FindElement(By.Id("year")).SendKeys("");
            driver.FindElement(By.CssSelector("html")).Click();
            driver.FindElement(By.Id("make")).SendKeys("ford");
            driver.FindElement(By.Id("model")).SendKeys("fiesta");
            driver.FindElement(By.Id("year")).SendKeys("2018");
            driver.FindElement(By.Id("submit")).Click();
            string message1 = driver.FindElement(By.Id("errors")).Text;
            Console.WriteLine(message1);
            driver.FindElement(By.Id("make")).Click();
            driver.FindElement(By.Id("carform")).Click();
            driver.FindElement(By.Id("model")).SendKeys("");
            driver.FindElement(By.Id("model")).Clear();
            driver.FindElement(By.Id("model")).SendKeys("f-150");
            driver.FindElement(By.Id("submit")).Click();
            string message2 = driver.FindElement(By.Id("errors")).Text;
            Console.WriteLine(message2);
            //Assert
            Assert.AreEqual(message1, "New Record Saved! Record Number: 1");
            Assert.AreEqual(message2, "New Record Saved! Record Number: 2");
        }
        [Test]
        public void Search_ClickSearchButton_ShowSavedRecords()
        {
            //Arrange
            driver.Navigate().GoToUrl("http://localhost:4000/");
            driver.Manage().Window.Size = new System.Drawing.Size(800, 824);
            //Act
            driver.FindElement(By.Id("homeToSearch")).Click();
            string message = driver.FindElement(By.Id("carlist")).Text;
            Console.WriteLine(message); //empty or not
            //Assert
            Assert.IsNotNull(message);
        }
        [Test]
        public void SearchLink_ClickTopRecordLink_GotoRelevantJDPowerPage()
        {
            //Arrange
            driver.Navigate().GoToUrl("http://localhost:4000/");
            driver.Manage().Window.Size = new System.Drawing.Size(783, 824);
            //Act
            driver.FindElement(By.Id("homeToSearch")).Click();
            vars["WindowHandles"] = driver.WindowHandles;
            string message = driver.FindElement(By.Id("0")).GetAttribute("href");
            Console.WriteLine(message);
            driver.FindElement(By.Id("0")).Click();
            vars["win6939"] = waitForWindow(2000);
            driver.SwitchTo().Window(vars["win6939"].ToString());
            //Assert
            Assert.AreEqual(message, "http://www.jdpower.com/cars/2012/ford/mustang");
        }
    }
}

